### ISSUE TITLE
The GPU's graphics card usage is also constantly increasing,

### ISSUE THREAD

**Issue by kunkunsheng** [dvlab-research/LLaMA-VID#57]
When using cli. py for inference, as the problem continues, the GPU's graphics card usage also increases. Is there any way to prevent the GPU's graphics memory from increasing

**Comment by yanwei-li** [comment]
Hi, I guess this issue is caused by concating multi-turn conversations in each forward. If your conversation has several turns, you can reduce the conversation in `conv`  in [this line](https://github.com/dvlab-research/LLaMA-VID/blob/d1074f3662a772d1b3c723416af59314ba593f67/llamavid/serve/cli.py#L118).

**Comment by kunkunsheng** [comment]
> 我想这个问题是由每个转发中的多轮对话引起的

How should I change the code so that each conversation is the first conversation for the model

**Comment by kunkunsheng** [comment]
> Hi, I guess this issue is caused by concating multi-turn conversations in each forward. If your conversation has several turns, you can reduce the conversation in `conv` in [this line](https://github.com/dvlab-research/LLaMA-VID/blob/d1074f3662a772d1b3c723416af59314ba593f67/llamavid/serve/cli.py#L118).

Thank you, it has been solved. Just clear the cache of the video memory and it will be fine.
