### ISSUE TITLE
Cannot reproduce Zero-shot Video-QA (MSVD)

### ISSUE THREAD

**Issue by dcahn12** [dvlab-research/LLaMA-VID#6]
Thanks for your contribution!

I tried to reproduce your result (Zero-shot VideoQA on MSVD dataset) with the given pretrained weights. (EVA-G & LLaVA1.5-VideoChatGPT-Instruct 7B).

But the result is completely different from your paper.
(Reproduced result is shown below)
![2023-12-08_00-33-14](https://github.com/dvlab-research/LLaMA-VID/assets/61134923/4827b2a0-5da8-45d2-b784-e8af0065ed08)

Can you check this?

**Comment by yanwei-li** [comment]
Hi, it seems a huge gap, could you please give more details? We use the this [model](https://huggingface.co/YanweiLi/llama-vid-7b-full-224-video-fps-1) and this [script](https://github.com/dvlab-research/LLaMA-VID/blob/main/scripts/video/eval/msvd_eval.sh) for evaluation.

**Comment by dcahn12** [comment]
I also used the same model (llama-vid-7b-full-224-video-fps-1) and employed the same script to generate responses to relevant questions. However, when evaluating GPT-based evaluations, I simply omitted the "--api_base" argument because it caused an error during the evaluation process. Could you please provide the model-generated answer responses for the MSVD-QA dataset?

**Comment by yanwei-li** [comment]
Hi, we provide the prediction in [pred.json](https://github.com/dvlab-research/LLaMA-VID/files/13608868/pred.json) and also GPT3.5 evaluated results in [results.json](https://github.com/dvlab-research/LLaMA-VID/files/13608869/results.json).
We also re-evaluate the model, because GPT-based evaluation may have performance bias (give different results at each turn), but still within an acceptable range:
<img width="300" alt="截屏2023-12-08 12 11 25" src="https://github.com/dvlab-research/LLaMA-VID/assets/24286910/6a7fd902-ff05-4a8e-abeb-030361e2e0d2">

**Comment by yanwei-li** [comment]
Close it now, please reopen it if you have further questions.

**Comment by Felix0805** [comment]
Hello，can you tell me where can I download the msvd dataset? Thank you very much.
